sudo: required
services:
  - docker
before_install:
  - docker pull node:8-onbuild

install:
  - docker image build -t probot-hello .

script:
  - docker run --rm probot-hello npm run test
  - docker run --rm probot-hello npm run lint

deploy:
  provider: heroku
  api_key: aace5fff-d753-4505-b997-9e4a72cb9cf6
  on: heroku_production
  app: probot-harshmalik9423
