sudo: required
services:
  - docker

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t probot-hello .

script:
  - docker container run --rm probot-hello npm run test
  - docker container run --rm probot-hello npm run lint

after_success:
  - docker image tag probot-hello probot-hello:$(git rev-parse HEAD)
